### ISSUE TITLE
SYCLE/ESIMD/[S,s]tencil*.cpp tests fail sporadically

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm-test-suite#155]
The test are failing both on compiler:
http://llvm-ci.intel.com:8080/job/SYCL_CI/job/intel/job/Win/job/Test_Suite/1249/display/redirect
And llvm-test-suite CI:
   http://pre-commit.llvm.intel.com:8010/job/LLVM-Test-Suite-CI/job/LLVM-Test-Suite-WIN/240/display/redirect

The test are going to be disabled until become stable.

**Comment by kychendev** [comment]
Pushed a fix in https://github.com/intel/llvm-test-suite/pull/178

**Comment by kychendev** [comment]
Passed test and merged.
