### ISSUE TITLE
SYCL :: Plugin/enqueue-arg-order-image.cpp fails on CUDA

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm-test-suite#173]
The test start to fail on CUDA BE after intel/llvm#3294

 e.g. http://pre-commit.llvm.intel.com:8010/job/LLVM-Test-Suite-CI/job/LLVM-Test-Suite-CUDA/239/display/redirect

**Comment by vladimirlaz** [comment]
The test has been parked as XFAIL to avoid false alarms in llvm-test-suite CI: https://github.com/intel/llvm-test-suite/pull/172

**Comment by sergey-semenov** [comment]
I'm a bit baffled as to why this failure only showed up after the patch, I consistently reproduce this on one of our CI machines both with and without the patch. The failure itself has to do with the test relying on host unified memory. Opened https://github.com/intel/llvm-test-suite/pull/174
