### ISSUE TITLE
SYCL :: ESIMD/api/simd_view_copy_move_assign.cpp timeouts on windows

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm-test-suite#664]
The test is temprorary disabled: http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/LLVM-Test-Suite-CI-TMP%2FLLVM-Test-Suite-CI-WIN/detail/LLVM-Test-Suite-CI-WIN/1310/pipeline/212

**Comment by v-klochkov** [comment]
The fix addressing the issue: https://github.com/intel/llvm-test-suite/pull/936
