### ISSUE TITLE
Implement tests for atomic memory orders

### ISSUE THREAD

**Issue by t4c1** [intel/llvm-test-suite#793]
Existing tests are fundamentally broken and are being removed in https://github.com/intel/llvm-test-suite/pull/783. New tests need to be designed and implemented.

**Comment by t4c1** [comment]
I looked into these tests, however no test I wrote actually failed when using wrong memory order (a test would only fail if compiler of device reordered instructions around the atomic). @steffenlarsen is there even interest in having such tests in the test suite?

**Comment by steffenlarsen** [comment]
I think they would be nice to have. Say we have a bug in the reordering it would be much easier to identify it in a small test rather than in production code. I don't think we need to test for all types though, so simple minimal tests would probably be good enough.
